In [1]:
import numpy as np

In [4]:
a = np.array([[10, 15]])
b = np.array([[20,9]])

print(a)
print(b)
# print()
a+b

[[10 15]]
[[20  9]]


array([[30, 24]])

In [5]:
a-b

array([[-10,   6]])

In [8]:
a * b

array([[200, 135]])

In [6]:
(a - b).T

array([[-10],
       [  6]])

In [9]:
# Create an Identity matrix 
I1 = np.eye(2)
I2 = np.eye(3)

print(I1, end = "= I1\n\n")
print(I2, end = "= I2\n\n")

[[1. 0.]
 [0. 1.]]= I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]= I2

